# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ForestRoads
                                 A QGIS plugin
 Create a network of forest roads based on zones to access, roads to connect
 them to, and a cost matrix.
 The code of the plugin is based on the "LeastCostPath" plugin available on
 https://github.com/Gooong/LeastCostPath. We thank their team for the template.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 10-07-2019
        copyright            : (C) 2019 by Clement Hardy
        email                : clem.hardy@outlook.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'clem.hardy@outlook.fr'
__date__ = 'Currently in work'
__copyright__ = '(C) 2019 by Clement Hardy'


# noinspection PyPep8Naming
# The classFactory function is read by QGIS to load the plugin.
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LeastCostPath class from file LeastCostPath.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    # The function will return our plugin, which contains two
    # functions that QGIS can launch : initGUI and unload, both
    # need to load or unload the plugin. See forestRoadNetwork_Main.py
    from .forestRoadNetwork_Main import forestRoadNetworkPlugin
    return forestRoadNetworkPlugin()
